import type { Metadata } from "next";
import { Geist, Geist_Mono, Volkhov } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/Navbar";
import Navbar2 from "@/components/Navbar/Navbar2";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const volkhov = Volkhov({
    variable: "--font-volkhov",
    subsets: ["latin"],
    weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${volkhov.variable} antialiased`}
      >
      {/*<Navbar />*/}
      <Navbar2 />
        {children}
      </body>
    </html>
  );
}
